### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by everinurmind** [everinurmind/Ruby-Group-Capstone-Project#27]
[Link to our Project](https://github.com/everinurmind/Ruby-Group-Capstone-Project/projects/1)

We are a team of 2:
@everinurmind works ``is a team member #1``
@ghreza-crypto ``is a team member #2``
We did divide ``team member 3`` tasks between us.

**Comment by GzimAsani** [comment]
### Hello, @everinurmind and @ghreza-crypto                    :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job adding description for each task +1: 

 ## Required Changes 

- [ ] Make sure to add all the tasks tasks for each bullet point and assign to both of you 
![image](https://github.com/everinurmind/Ruby-Group-Capstone-Project/assets/62705947/b21eb968-cc74-4b3e-8e2e-40df204e8064)
- [ ] Team member two has significantly more points that the first member, it is not good if a team member has 5+ more points than the other
- [ ] Please be reminded to have a task for each of these bullet points, meaning each member needs to have 9 tasks plus the division of the team member 3 which has 9 tasks as well plus the group tasks 
![image](https://github.com/everinurmind/Ruby-Group-Capstone-Project/assets/62705947/28fa9867-864f-4d09-a8ea-34f2937778fe)


 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N/A



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by laiifuu** [comment]
# STATUS: APPROVED :heavy_check_mark: 

## Hi team :wave: 
Your project is complete! 
Congratulations! 🎉 

![friends-joey](https://github.com/everinurmind/Ruby-Group-Capstone-Project/assets/93520178/25a29a8c-c5ff-447c-8c9f-79f0c0b43eb2)


## Highlights
- [x] Each task has a title, a description and at least one assignee :heavy_check_mark:  
- [x] Tasks distributed equally between the team members :heavy_check_mark: 

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
